#!/bin/bash
clear

# --- Otomatik Yapılandırma ---
# SSH yapılandırmasında 'Banner' satırı var mı diye kontrol et.
chk=$(cat /etc/ssh/sshd_config | grep Banner)

# Eğer Dropbear servisi çalışıyorsa, onun da banner dosyasını kullanmasını sağla.
[[ $(netstat -nltp|grep 'dropbear' | wc -l) != '0' ]] && {
    local="/etc/bannerssh"
    # Eğer Dropbear ayar dosyasında banner satırı yoksa, ekle.
    [[ $(grep -wc $local /etc/default/dropbear) = '0' ]] && echo 'DROPBEAR_BANNER="/etc/bannerssh"' >> /etc/default/dropbear
}

# Eğer SSH yapılandırmasında 'Banner' satırı zaten varsa, dosya yolunu oradan al.
[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
    local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
} || {
    # Eğer SSH yapılandırmasında 'Banner' satırı yoksa, varsayılan yolu ekle.
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/ssh/sshd_config) = '0' ]] && echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
}

# --- Menü Arayüzü ---
# Başlık metnini mavi arka plan üzerine beyaz ve kalın olarak yazdır.
echo -e "\E[44;1;37m        ㅤ🐉ㅤBANNER YÖNETİCİSİㅤ🐉ㅤ         \E[0m"
echo ""

# Manuel banner ekleme yöntemini açıkla.
echo -e "\033[1;32m◇───MANUEL BANNER EKLEME YÖNTEMİ───◇"
echo -e "\033[1;37m◇ 1. Adım:- Aşağıdaki komutu kopyalayıp gönderinㅤ👇ㅤ"
echo -e "\033[1;31msudo nano /etc/bannerssh"
echo -e "\033[1;37m◇ BANNER'INIZI HTML METNİ OLARAK YAPIŞTIRIN"
echo -e "\033[1;37m◇ 2. Adım:- Kaydetmek için CTRL+O, çıkmak için CTRL+X yapın"
echo ""
echo -e "\033[1;32m Veya"
echo ""

# Kolay banner ekleme yöntemini göster.
echo -e "\033[1;32m◇───KOLAY BANNER EKLEME YÖNTEMİ───◇"
echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;37m • \033[1;33mBANNER EKLE"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;37m • \033[1;33mBANNER'I KALDIR"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;37m • \033[1;33mGERİ DÖN"
echo ""

# Kullanıcıdan bir seçim yapmasını iste.
echo -ne "\033[1;32m◇ NE YAPMAK İSTERSİNİZ\033[1;31m ?\033[1;37m : "; read resp

# --- Kullanıcı Seçimlerini İşleme ---
if [[ "$resp" = "1" ]]; then
    echo ""
    # Banner metnini al.
    echo -ne "\033[1;32m◇ GÖRÜNMESİNİ İSTEDİĞİNİZ MESAJ NEDİR\033[1;31m ?\033[1;37m : "; read msg1
    if [[ -z "$msg1" ]]; then
        echo -e "\n\033[1;31m◇ Boş veya geçersiz alan!\033[0m"
        sleep 2
        banner # Bu script'i yeniden başlat
    fi

    # Yazı tipi boyutunu seçtir.
    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m KÜÇÜK YAZI TİPİ"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m ORTA YAZI TİPİ"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m BÜYÜK YAZI TİPİ"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m DEV YAZI TİPİ"
    echo ""
    echo -ne "\033[1;32m◇ YAZI TİPİ BOYUTU NE OLSUN\033[1;31m ?\033[1;37m : "; read opc
    if [[ "$opc" = "1" ]] || [[ "$opc" = "01" ]]; then _size='6'
    elif [[ "$opc" = "2" ]] || [[ "$opc" = "02" ]]; then _size='4'
    elif [[ "$opc" = "3" ]] || [[ "$opc" = "03" ]]; then _size='3'
    elif [[ "$opc" = "4" ]] || [[ "$opc" = "04" ]]; then _size='1'
    fi

    # Yazı tipi rengini seçtir.
    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m MAVİ"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m YEŞİL"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m KIRMIZI"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m SARI"
    echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m PEMBE"
    echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CAMGÖBEĞİ"
    echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m TURUNCU"
    echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m MOR"
    echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m SİYAH"
    echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m RENKSİZ"
    echo ""
    echo -ne "\033[1;32m◇ RENGİ NE OLSUN\033[1;31m ?\033[1;37m : "; read ban_cor
    
    # Seçilen renge göre HTML kodunu oluştur ve banner dosyasına yaz.
    if [[ "$ban_cor" = "1" ]] || [[ "$ban_cor" = "01" ]]; then echo "<h$_size><font color='blue'>$msg1" > $local
    elif [[ "$ban_cor" = "2" ]] || [[ "$ban_cor" = "02" ]]; then echo "<h$_size><font color='green'>$msg1" > $local
    elif [[ "$ban_cor" = "3" ]] || [[ "$ban_cor" = "03" ]]; then echo "<h$_size><font color='red'>$msg1" > $local
    elif [[ "$ban_cor" = "4" ]] || [[ "$ban_cor" = "04" ]]; then echo "<h$_size><font color='yellow'>$msg1" > $local
    elif [[ "$ban_cor" = "5" ]] || [[ "$ban_cor" = "05" ]]; then echo "<h$_size><font color='#F535AA'>$msg1" > $local
    elif [[ "$ban_cor" = "6" ]] || [[ "$ban_cor" = "06" ]]; then echo "<h$_size><font color='cyan'>$msg1" > $local
    elif [[ "$ban_cor" = "7" ]] || [[ "$ban_cor" = "07" ]]; then echo "<h$_size><font color='#FF7F00'>$msg1" > $local
    elif [[ "$ban_cor" = "8" ]] || [[ "$ban_cor" = "08" ]]; then echo "<h$_size><font color='#9932CD'>$msg1" > $local
    elif [[ "$ban_cor" = "9" ]] || [[ "$ban_cor" = "09" ]]; then echo "<h$_size><font color='black'>$msg1" > $local
    elif [[ "$ban_cor" = "10" ]]; then
        echo "<h$_size>$msg1</h$_size>" > $local
        /etc/init.d/ssh restart > /dev/null 2>&1
        echo -e "\n\033[1;32m◇ BANNER EKLENDİ!\033[0m"
        sleep 2
        menu
    else
        echo -e "\n\033[1;31m◇ Geçersiz seçenek!\033[0m"
        sleep 2
        banner
    fi
    
    # HTML etiketlerini kapat.
    echo "</font></h$_size>" >> $local
    
    # Değişikliklerin geçerli olması için servisleri yeniden başlat.
    service ssh restart > /dev/null 2_>&_1 && service dropbear restart > /dev/null 2_>&_1
    echo -e "\n\033[1;32m◇ BANNER EKLENDİ!\033[0m"
    unset ban_cor

elif [[ "$resp" = "2" ]]; then
    # Banner dosyasının içini boşaltarak banner'ı kaldır.
    echo " " > $local
    echo -e "\n\033[1;32m◇ BANNER SİLİNDİ!\033[0m"
    service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
    sleep 2
    menu
elif [[ "$resp" = "3" ]]; then
    # Ana menüye dön.
    menu
else
    # Geçersiz seçenek girilirse uyar.
    echo -e "\n\033[1;31m◇ Geçersiz seçenek!\033[0m"
    sleep 2
    banner
fi