#!/bin/bash
clear
# Kullanıcıya kaldırma işlemini onaylat.
echo -e "\033[1;32m🐉ㅤCyux VPS Yöneticisiㅤ🐉ㅤKALDIRILSIN MI?\033[1;33m"
read -p "Kaldırmak istiyor musunuz? [e/h] " resp

# Eğer kullanıcı 'e' veya 'E' ile cevap verirse...
if [[ "$resp" = e || "$resp" = E ]]; then
    # --- Kaldırma İşlemleri ---
    
    # Yönetim paneli tarafından kurulan tüm paketleri sistemden tamamen kaldır.
    apt-get purge screen -y > /dev/null 2>&1
    apt-get purge nmap -y > /dev/null 2>&1
    apt-get purge figlet -y > /dev/null 2>&1
    apt-get purge squid squid3 -y > /dev/null 2>&1
    apt-get purge dropbear -y > /dev/null 2>&1
    apt-get purge apache2 -y > /dev/null 2>&1
    
    # /bin dizinine kopyalanan tüm komut dosyalarını sil.
    rm /bin/criarusuario /bin/expcleaner /bin/sshlimiter /bin/addhost /bin/listar /bin/sshmonitor /bin/ajuda /bin/menu /bin/OpenVPN /bin/userbackup /bin/tcpspeed /bin/badvpn /bin/otimizar /bin/speedtest /bin/trafego /bin/banner /bin/limit /bin/limite /bin/senharoot /bin/reiniciarservicos /bin/reiniciarsistema /bin/attscript /bin/criarteste /bin/socks  /bin/DropBear /bin/alterarlimite /bin/alterarsenha /bin/remover /bin/detalhes /bin/mudardata /bin/botssh /bin/infousers /bin/droplimiter /bin/conexao /bin/versao > /dev/null 2>&1
    
    # Ana yapılandırma klasörünü (/etc/VPSManager) ve içindeki her şeyi sil.
    rm -rf /etc/VPSManager > /dev/null 2>&1
    
    clear
    
    # Veda mesajını göster.
    echo -e "\033[1;36m🐉ㅤCyux VPS Yöneticisi'niㅤ🐉ㅤkullandığınız için teşekkürler!\033[1;33m"
    sleep 2
    
    # Komut geçmişini temizle ve çıkış yap.
    cat /dev/null > ~/.bash_history && history -c && exit 0
else
    # Eğer kullanıcı işlemi iptal ederse, ana menüye dön.
    echo -e "\033[1;32mÇıkmak için CTRL+C yapın\033[1;33m"
    sleep 3
    menu
fi