#!/bin/bash
clear
# Başlık metnini mavi arka plan üzerine beyaz ve kalın olarak yazdır.
echo -e "\E[44;1;37m           🐉ㅤℹㅤVPS BİLGİLERİㅤℹㅤ🐉           \E[0m"
echo ""

# --- İşletim Sistemi Bilgileri ---
# /etc/lsb-release dosyası varsa, bu Debian/Ubuntu tabanlı bir sistemdir.
if [ -f /etc/lsb-release ]; then
    echo -e "\033[1;31m• \033[1;32mİŞLETİM SİSTEMİ\033[1;31m •\033[0m"
    echo ""
    # Gerekli bilgileri dosyadan oku ve ekrana yazdır.
    name=$(cat /etc/lsb-release |grep DESCRIPTION |awk -F = {'print $2'})
    codename=$(cat /etc/lsb-release |grep CODENAME |awk -F = {'print $2'})
    echo -e "\033[1;33mVersiyon: \033[1;37m$name"
    echo -e "\033[1;33mKod Adı: \033[1;37m$codename"
    echo -e "\033[1;33mÇekirdek (Kernel): \033[1;37m$(uname -s)"
    echo -e "\033[1;33mÇekirdek Sürümü: \033[1;37m$(uname -r)"
    if [ -f /etc/os-release ]; then
        devlike=$(cat /etc/os-release |grep LIKE |awk -F = {'print $2'})
        echo -e "\033[1;33mTüretildiği Sistem: \033[1;37m$devlike"
        echo ""
    fi
else
    # Eğer /etc/lsb-release yoksa, başka bir Linux dağıtımıdır.
    system=$(cat /etc/issue.net)
    echo -e "\033[1;31m• \033[1;32mİŞLETİM SİSTEMİ\033[1;31m •\033[0m"
    echo ""
    echo -e "\033[1;33mVersiyon: \033[1;37m$system"
    echo ""
fi

# --- İşlemci (CPU) Bilgileri ---
if [ -f /proc/cpuinfo ]; then
    # Anlık CPU kullanımını hesapla.
    uso=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
    echo -e "\033[1;31m• \033[1;32mİŞLEMCİ\033[1;31m •\033[0m"
    echo ""
    # Gerekli bilgileri /proc/cpuinfo dosyasından oku ve ekrana yazdır.
    modelo=$(cat /proc/cpuinfo |grep "model name" |uniq |awk -F : {'print $2'})
    cpucores=$(grep -c cpu[0-9] /proc/stat)
    cache=$(cat /proc/cpuinfo |grep "cache size" |uniq |awk -F : {'print $2'})
    echo -e "\033[1;33mModel:\033[1;37m$modelo"
    echo -e "\033[1;33mÇekirdek Sayısı:\033[1;37m $cpucores"
    echo -e "\033[1;33mÖnbellek Boyutu:\033[1;37m$cache"
    echo -e "\033[1;33mMimari: \033[1;37m$(uname -p)"
    echo -e "\033[1;33mKullanım: \033[37m$uso"
    echo ""
else
    echo -e "\033[1;32mİŞLEMCİ\033[0m"
    echo ""
    echo "Bilgiler alınamadı."
fi

# --- RAM Bellek Bilgileri ---
if free 1>/dev/null 2>/dev/null; then
    # RAM bilgilerini 'free' komutuyla al ve formatla.
    ram1=$(free -h | grep -i mem | awk {'print $2'}) # Toplam
    ram2=$(free -h | grep -i mem | awk {'print $4'}) # Boş
    ram3=$(free -h | grep -i mem | awk {'print $3'}) # Kullanılan
    usoram=$(free -m | awk 'NR==2{printf "%.2f%%\t\t", $3*100/$2 }') # Kullanım yüzdesi

    echo -e "\033[1;31m• \033[1;32mRAM BELLEK\033[1;31m •\033[0m"
    echo ""
    echo -e "\033[1;33mToplam: \033[1;37m$ram1"
    echo -e "\033[1;33mKullanımda: \033[1;37m$ram3"
    echo -e "\033[1;33mBoşta: \033[1;37m$ram2"
    echo -e "\033[1;33mKullanım Yüzdesi: \033[37m$usoram"
    echo ""
else
    echo -e "\033[1;32mRAM BELLEK\033[0m"
    echo ""
    echo "Bilgiler alınamadı."
fi

# --- Aktif Servisler ve Portlar ---
echo -e "\033[1;31m• \033[1;32mÇALIŞAN SERVİSLER\033[1;31m •\033[0m"
echo ""
# 'lsof' komutu ile dinlemede olan tüm servisleri ve portlarını bul.
PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
# Bulunan servisleri ve portları döngü ile ekrana yazdır.
for porta in `echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq`; do
    svcs=$(echo -e "$PT" | grep -w "$porta" | awk '{print $1}' | uniq)
    echo -e "\033[1;33mServis \033[1;37m$svcs \033[1;33mPort \033[1;37m$porta"
done