#!/bin/bash
clear

# --- FONKSİYON: Arka planda bir komut çalıştırırken bekleme animasyonu gösterir ---
fun_prog ()
{
    # Çalıştırılacak komutu bir diziye ata.
    comando[0]="$1"
    # Komutu arka planda çalıştır.
    ${comando[0]} > /dev/null 2>&1 &
    
    # İmleci gizle.
    tput civis
    echo -ne "\033[1;32m.\033[1;33m.\033[1;31m. \033[1;32m"
    
    # Komut çalışırken dönen bir animasyon göster.
    while [ -d /proc/$! ]; do
        for i in / - \\ \|; do
            sleep .1
            echo -ne "\e[1D$i"
        done
    done
    
    # İşlem bittiğinde onayla ve imleci tekrar görünür yap.
    tput cnorm
    echo -e "\e[1DTAMAM"
}

# --- Servisleri Yeniden Başlatma İşlemleri ---
# Her bir servis için, önce yeniden başlatıldığını belirten bir mesaj yazdır,
# ardından 'fun_prog' fonksiyonu ile yeniden başlatma komutunu çalıştır.

echo -ne "\033[1;33m◇ OPENSSH YENİDEN BAŞLATILIYOR "; fun_prog 'service ssh restart'
echo ""
sleep 1

# Eğer Squid (sürüm 2/3) kuruluysa, yeniden başlat.
if [[ -e /etc/squid/squid.conf ]]; then
    echo -ne "\033[1;33m◇ SQUID PROXY YENİDEN BAŞLATILIYOR "; fun_prog 'service squid restart'
    echo ""
    sleep 1
elif [[ -e /etc/squid3/squid.conf ]]; then
    echo -ne "\033[1;33m◇ SQUID PROXY YENİDEN BAŞLATILIYOR "; fun_prog 'service squid3 restart'
    echo ""
    sleep 1
fi

# Eğer SSL Tüneli (stunnel) kuruluysa, yeniden başlat.
if [[ -e /etc/stunnel/stunnel.conf ]]; then
    echo -ne "\033[1;33m◇ SSL TÜNELİ YENİDEN BAŞLATILIYOR "; fun_prog 'service stunnel4 restart'
    echo ""
    sleep 1
fi

# Eğer Dropbear kuruluysa, yeniden başlat.
if [[ -e /etc/init.d/dropbear ]]; then
    echo -ne "\033[1;33m◇ DROPBEAR YENİDEN BAŞLATILIYOR "; fun_prog 'service dropbear restart'
    echo ""
    sleep 1
fi

# Eğer OpenVPN kuruluysa, yeniden başlat.
if [[ -e /etc/openvpn/server.conf ]]; then
    echo -ne "\033[1;33m◇ OPENVPN YENİDEN BAŞLATILIYOR "; fun_prog 'service openvpn restart'
    echo ""
    sleep 1
fi

# Eğer Apache2 web sunucusu çalışıyorsa, yeniden başlat.
if netstat -nltp|grep 'apache2' > /dev/null; then
    echo -ne "\033[1;33m◇ APACHE2 YENİDEN BAŞLATILIYOR "; fun_prog '/etc/init.d/apache2 restart'
    echo ""
    sleep 1
fi

# Son başarı mesajını göster.
echo -e "\033[1;32m◇ SERVİSLER BAŞARIYLA YENİDEN BAŞLATILDI!\033[0m"
sleep 1