#!/bin/bash

# Ekrana kırmızı renkte bir uyarı mesajı yazdır.
echo -e "\033[1;31m◇ DİKKAT!!\033[0m"
echo " "
# Şifrenin ne için kullanılacağını açıkla.
echo -e "\033[1;33m◇ Bu şifre, sunucunuza giriş yapmak için kullanılacaktır.
\033[0m"
# Kullanıcıdan yeni şifreyi girmesini iste.
echo -e "\033[1;32m◇ DEVAM ETMEK İÇİN YENİ ŞİFREYİ GİRİN...\033[0m"

# Kullanıcıdan şifreyi oku.
read -p ": " pass

# 'passwd' komutuna şifreyi iki kez göndererek otomatik olarak değiştir.
(echo $pass; echo $pass) | passwd 2>/dev/null

# 1 saniye bekle.
sleep 1s

# Başarı mesajını göster.
echo -e "\033[1;31m◇ ŞİFRE BAŞARIYLA DEĞİŞTİRİLDİ!\033[0m"

# 5 saniye bekle.
sleep 5s

# Ana dizine dön.
cd

# Ekranı temizle.
clear