#!/bin/bash
clear
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CORTITLE='\033[1;41m'
SCOLOR='\033[0m'
banner='
 ___ _    _____      _____  _  _ ___ 
/ __| |  / _ \ \    / /   \| \| / __|
\__ \ |_| (_) \ \/\/ /| |) | .  \__ \
|___/____\___/ \_/\_/ |___/|_|\_|___/'

echo -e "${CORTITLE}◇───────────────────────────────────────────────◇${SCOLOR}" 
echo -e "${CORTITLE}🐉ㅤCyuX VPS Yöneticisi SLOW DNS İstemcisi 🐉${SCOLOR}"
echo -e "${CORTITLE}◇───────────────────────────────────────────────◇${SCOLOR}" 
echo -e "${RED}$banner${SCOLOR}"
[[ ! -e dns ]] && {
    yes| termux-setup-storage > /dev/null 2>&1
    unset LD_PRELOAD > /dev/null 2>&1
    cd $HOME
    mv slowdns $PREFIX/bin/slowdns
    chmod +x $PREFIX/bin/slowdns
    [[ $(grep -c 'slowdns' $PREFIX/etc/profile) == '0' ]] && echo 'slowdns' >> $PREFIX/etc/profile
    echo -e "\n${GREEN}SKRİPT İNDİRİLİYOR LÜTFEN BEKLEYİN! ${SCOLOR}"
    curl -O https://github.com/github.com/januda-ui/DRAGON-VPS-MANAGER/raw/main/Modulos/dns > /dev/null 2>&1
    echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}SKRİPT İNDİRİLDİ! BİR SONRAKİ SEFER\nSADECE ŞU KOMUTU ÇALIŞTIRIN ${RED}(${GREEN}slowdns${RED})\n${YELLOW}ÇEVRİMDIŞI OLSA BİLE!${SCOLOR}"
    chmod +x dns
}
[[ ! -e $HOME/credenciais ]] && {
    ns=$1
    [[ -z "$ns" ]] && {
        echo -e "\n${RED}EKSİK KOMUT${SCOLOR}"
        exit 0
    }
    chave=$2
    [[ -z "$chave" ]] && {
        echo -e "\n${RED}EKSİK KOMUT${SCOLOR}"
        exit 0
    }
    echo -e "$ns\n$chave" > $HOME/credenciais
} || {
    perg=$(echo "${SCOLOR}[e/h]: ")
    echo -e "\n${YELLOW}SKRİPT ZATEN BİR SUNUCU İLE YAPILANDIRILMIŞ\nVE BAĞLANTIYA HAZIR"
    read -p "$(echo -e "${GREEN}AYNI SUNUCU İLE DEVAM ETMEK İSTİYOR MUSUNUZ?${SCOLOR} [e/h]: ")" -e -i e opc
    [[ "$opc" != @(e|evet|E|EVET) ]] && {
        rm $HOME/credenciais dns > /dev/null 2>&1
        rm $PREFIX/bin/slowdns > /dev/null 2>&1
        sed -i '/slowdns/d' $PREFIX/etc/profile > /dev/null 2>&1
        echo -e "\n${RED}SKRİPT KALDIRILDI!${SCOLOR}"
        rm slowdns > /dev/null 2>&1
        exit 0
    } || {
        unset LD_PRELOAD > /dev/null 2>&1
        ns=$(sed -n 1p $HOME/credenciais)
        chave=$(sed -n 2p $HOME/credenciais)
    }
}
dns=$3
[[ -z "$dns" ]] && {
    dns='187.50.250.115'
}
echo -ne "\n${RED}[${YELLOW}!${RED}] ${YELLOW}DEVAM ETMEK İÇİN LÜTFEN SADECE\n${RED}(${YELLOW}MOBİL VERİ${RED}) ${YELLOW}KULLANDIĞINIZDAN EMİN OLUN\n${YELLOW}DEVAM ETMEK İÇİN ${GREEN}ENTER ${YELLOW}TUŞUNA BASIN.. ${SCOLOR}"; read
$HOME/dns -udp ${dns}:53 -pubkey ${chave} ${ns} 127.0.0.1:2222 > /dev/null 2>&1 &
echo -e "\n${RED}[${GREEN}✓${RED}]${SCOLOR} - ${GREEN}SLOWDNS BAŞLATILDI!${SCOLOR} - ${RED}[${GREEN}✔${RED}]\n\n${RED}[${YELLOW}!${RED}] ${YELLOW}ŞİMDİ BİR VPN UYGULAMASINA BAĞLANIN\nVEYA BAĞLANTIYI KESMEK İÇİN ${GREEN}ENTER ${RED}TUŞUNA BASIN ${SCOLOR}"; read
piddns=$(ps x| grep -w 'dns' | grep -v 'grep'| awk -F' ' {'print $1'})
[[ ${piddns} != '' ]] && kill ${piddns} > /dev/null 2>&1